/* Dedicated management workstreams. All aggregates follow the selected MES orders. */
const total=(rows,key)=>rows.reduce((s,r)=>s+(Number(r[key])||0),0);
const ratio=(n,d)=>d>0?n/d:null;
const percentage=(n,d)=>d>0?100*n/d:null;
const panel=(title,body,note='')=>`<div class="panel"><h3>${esc(title)}</h3>${note?`<p class="desc">${esc(note)}</p>`:''}${body}</div>`;
const cards=items=>`<div class="kpis">${items.map(x=>kpi(...x)).join('')}</div>`;
const dataTable=(labels,rows)=>table(labels.map(t=>({t})),rows.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`));
function selectedPeriods(c){const ids=new Set(c.f.map(r=>r.order));return D.periods.filter(r=>ids.has(r.order)&&(state.machine==='ALL'||r.machine===state.machine)&&(state.product==='ALL'||r.product===state.product)&&(state.shift==='ALL'||r.shift===state.shift))}
function lostHours(r){return Math.max(0,r.usageHours-r.productionHours)}
function reasonRows(c){const ids=new Set(c.f.map(r=>r.order)),groups=new Map();for(const r of D.stoppages){if(!ids.has(r.order)||(state.machine!=='ALL'&&r.machine!==state.machine))continue;const v=groups.get(r.reason)||{reason:r.reason,minutes:0,events:0,rows:0};v.minutes+=r.minutes;v.events+=r.events||0;v.rows++;groups.set(r.reason,v)}let running=0;const rr=[...groups.values()].sort((a,b)=>b.minutes-a.minutes),sum=total(rr,'minutes');return rr.map(r=>({...r,cumulative:percentage(running+=r.minutes,sum)}))}
function reconciliationStatus(r){if(r.excelQty==null)return 'MES only';if(r.qtyDeltaPct==null)return 'Undefined % (Excel quantity zero)';const flags=[];if(Math.abs(r.qtyDeltaPct)>5)flags.push('Quantity >5%');if([r.startGapMin,r.endGapMin,r.mesDurationMin!=null&&r.excelDurationMin!=null?r.mesDurationMin-r.excelDurationMin:null].some(v=>v!=null&&Math.abs(v)>60))flags.push('Time >60 min');if([r.startGapMin,r.endGapMin,r.excelDurationMin].some(v=>v==null))flags.push('Time incomplete');return flags.join(' · ')||'Within thresholds'}
function renderReconciliation(c){const global=Object.entries(state).every(([k,v])=>k==='tab'||v==='ALL');return section('MES vs Operator Excel — Data Reliability','Normalized order keys. Match rate = matched / MES orders. Time exceptions use a 60-minute threshold; duration is elapsed first start to last end, including gaps.')+cards([
 ['MES orders',fmt(c.f.length)],['Matched orders',fmt(c.matched.length)],['MES-only orders',fmt(c.f.length-c.matched.length)],['Match rate',fmt(percentage(c.matched.length,c.f.length),1),'%'],['Excel orders (all)',fmt(D.summary.excelOrders),'','Global Excel scope'],['Excel-only orders (all)',fmt(D.excelOnly.length),'','No MES machine, shift or size association']
 ])+panel('Order reconciliation',dataTable(['Order','MES quantity','Excel quantity','Variance %','MES start / end','Excel start / end','MES min','Excel min','Status'],[...c.f].sort((a,b)=>(Math.abs(b.qtyDeltaPct)||0)-(Math.abs(a.qtyDeltaPct)||0)).map(r=>[r.order,fmt(r.produced),fmt(r.excelQty),fmt(r.qtyDeltaPct,1),`${r.start||'—'} / ${r.end||'—'}`,`${r.excelStart||'—'} / ${r.excelEnd||'—'}`,fmt(r.mesDurationMin,1),fmt(r.excelDurationMin,1),reconciliationStatus(r)])))+panel('Excel-only records — global scope',dataTable(['Order','Product','Quantity','Start','End'],D.excelOnly.map(r=>[r.order,r.product,fmt(r.produced),r.start||'—',r.end||'—'])),global?'Included in the global Excel total.':'MES filters cannot be applied to records without a MES match.');}
function renderDelays(c){const periods=selectedPeriods(c),run=c.f.filter(r=>r.plannedRunMin>0),delayed=run.filter(r=>r.usageHours*60>r.plannedRunMin),gap=run.reduce((s,r)=>s+Math.max(0,r.usageHours*60-r.plannedRunMin),0),loss=periods.reduce((s,r)=>s+lostHours(r),0);const groups=key=>{const g={};for(const r of periods){const k=key(r);g[k]=(g[k]||0)+lostHours(r)}return Object.entries(g).sort(([a],[b])=>a.localeCompare(b)).map(([label,value])=>({label,value}))};return section('Production Delay & Lost Production Time','Expected runtime = ordered quantity / order target rate. Usage minus expected runtime is a diagnostic proxy, not schedule lateness. Non-production time = max(usage − production, 0); these measures overlap and must not be added.')+cards([
 ['Expected runtime',fmt(total(run,'plannedRunMin')/60,1),'h',`${run.length}/${c.f.length} orders with target data`],['Actual usage',fmt(total(run,'usageHours'),1),'h','Same orders with target data'],['Above expected runtime',fmt(gap/60,1),'h','Positive differences only'],['Orders above expected',fmt(delayed.length)],['Average excess',fmt(ratio(gap,delayed.length),1),'min','Among orders above expected'],['Non-production time',fmt(loss,1),'h','Period-level usage − production'],['Availability proxy',fmt(percentage(total(periods,'productionHours'),total(periods,'usageHours')),1),'%']
 ])+`<div class="grid3">${panel('Monthly non-production hours',timeTrend(groups(r=>r.day.slice(0,7))))}${panel('Daily non-production hours',timeTrend(groups(r=>r.day)),'Period dates with recorded activity; missing days are not treated as zero')}${panel('By recorded shift',barList(groups(r=>r.shift),' h'),'Unknown shifts remain visible; no shift is inferred.')}</div>`+panel('Largest runtime overruns',dataTable(['Order','Machine','Product','Expected min','Usage min','Excess min','Excess %','Availability %','Top recorded reason'],[...run].sort((a,b)=>(b.usageHours*60-b.plannedRunMin)-(a.usageHours*60-a.plannedRunMin)).map(r=>[r.order,r.machine,r.product,fmt(r.plannedRunMin,1),fmt(r.usageHours*60,1),fmt(Math.max(0,r.usageHours*60-r.plannedRunMin),1),fmt(100*Math.max(0,r.usageHours*60-r.plannedRunMin)/r.plannedRunMin,1),fmt(r.availability,1),r.topReason||'—'])),'Reason is an investigation clue; it does not establish the cause of a runtime overrun.');}
function pareto(rows){if(!rows.length)return '<div class="empty">No stoppages for current filters</div>';const rr=rows.slice(0,12),max=Math.max(...rr.map(r=>r.minutes),1),W=720,H=300,p=42,bw=(W-2*p)/rr.length;return `<svg viewBox="0 0 ${W} ${H}" class="svgchart" role="img" aria-label="Stoppage Pareto: bars show minutes; amber line shows cumulative percent"><text x="${p}" y="16" class="tick">Minutes (bars) · cumulative % (line, right axis)</text>${rr.map((r,i)=>`<rect x="${p+i*bw+3}" y="${H-p-r.minutes/max*(H-2*p)}" width="${bw-6}" height="${r.minutes/max*(H-2*p)}" fill="#5a9cff"><title>${esc(r.reason)}: ${fmt(r.minutes,1)} min; cumulative ${fmt(r.cumulative,1)}%</title></rect><text x="${p+i*bw+bw/2}" y="${H-20}" text-anchor="middle" class="tick">${i+1}</text>`).join('')}<polyline points="${rr.map((r,i)=>`${p+i*bw+bw/2},${H-p-r.cumulative/100*(H-2*p)}`).join(' ')}" class="line-b"/><text x="3" y="${p}" class="tick">${fmt(max)}</text><text x="${W-35}" y="${p}" class="tick">100%</text><text x="${W-30}" y="${H-p}" class="tick">0%</text></svg>`}
function renderStoppages(c){const rr=reasonRows(c),minutes=total(rr,'minutes'),events=total(rr,'events'),p=selectedPeriods(c);return section('Stoppage / Root-Cause Analysis','Reason Pareto uses type-1 MES records. Technical and organizational totals come from production periods and may overlap reason totals. No validated category key links reasons to Setup, Cleaning, Changeover and Other; raw reason labels are retained.')+cards([
 ['Recorded stoppage',fmt(minutes,1),'min'],['Recorded disturbances',fmt(events),'','Sum of source stoppage_count'],['Average disturbance',fmt(ratio(minutes,events),1),'min'],['Technical (periods)',fmt(total(p,'technicalMin'),1),'min'],['Organizational (periods)',fmt(total(p,'organizationalMin'),1),'min'],['Top loss reason',rr[0]?.reason||'—']
 ])+panel('Setup, cleaning and changeover — operator records',dataTable(['Loss category','Reported minutes','Source scope'],[['Setup',fmt(total(c.matched,'manualSetupMin'),1),'Matched operator Excel orders'],['Cleaning',fmt(total(c.matched,'manualCleaningMin'),1),'Matched operator Excel orders'],['Changeover',fmt(total(c.matched,'manualChangeoverMin'),1),'Machine changeover + Wechsel 1–3'],['Other / unmapped','Not classified','Raw MES reasons retained below']]),'Manual row totals are a separate reporting source. Blank cells are treated as no recorded time; operator entries may overlap MES stoppages. Do not add these totals to MES losses.')+`<div class="grid2">${panel('Stoppage Pareto',pareto(rr),'Top 12 bars; cumulative percentage uses all filtered reasons. Numbers map to the table below.')}${panel('Top 5 loss reasons',barList(rr.map(r=>({label:r.reason,value:r.minutes})),' min',5),'Output lost is unavailable without a validated rate at each stoppage. Overlapping events can inflate recorded time.')}</div>`+panel('Reason details',dataTable(['Rank','Reason','Minutes','Disturbances','Average min','Cumulative %'],rr.map((r,i)=>[i+1,r.reason,fmt(r.minutes,1),fmt(r.events),fmt(ratio(r.minutes,r.events),1),fmt(r.cumulative,1)])));}
function renderStaffing(c){const p=selectedPeriods(c),groups=new Map();for(const r of p){const v=groups.get(r.shift)||{shift:r.shift,usageHours:0,employeeHours:0,produced:0,productionHours:0,orders:new Set()};for(const k of ['usageHours','employeeHours','produced','productionHours'])v[k]+=r[k];v.orders.add(r.order);groups.set(r.shift,v)}const hours=total(p,'employeeHours');return section('Staffing Planning vs Production Performance','Actual labor = WorkerCount × period usage hours. Planned staffing is not supplied. Missing worker counts cannot be distinguished from zero in this source; productivity is provisional. Association does not prove understaffing or overstaffing.')+cards([
 ['Recorded labor',fmt(hours,1),'h'],['Output / labor hour',fmt(ratio(total(p,'produced'),hours),1),'units'],['Average headcount',fmt(ratio(hours,total(p,'usageHours')),1),'','Weighted by usage time'],['Planned staffing','Unavailable'],['Shift completeness',fmt(D.quality.shiftCompletenessPct,1),'%','Global source coverage']
 ])+`<div class="grid2">${panel('Staffing vs throughput',scatter(c.valid,'avgWorkers','grossRate','Average headcount','Units / minute'))}${panel('Output by recorded shift',barList([...groups.values()].map(r=>({label:r.shift,value:r.produced}))))}</div>`+panel('Shift productivity',dataTable(['Shift','Orders','Output','Average workers','Labor hours','Units / labor h','Non-production h'],[...groups.values()].map(r=>[r.shift,r.orders.size,fmt(r.produced),fmt(ratio(r.employeeHours,r.usageHours),1),fmt(r.employeeHours,1),fmt(ratio(r.produced,r.employeeHours),1),fmt(lostHours(r),1)])))+panel('Order staffing and performance',dataTable(['Order','Machine','Product','Workers (avg)','Units / avg worker','Production h / avg worker','Units / labor h','Non-production h','Stoppage min','Review signal'],[...c.valid].sort((a,b)=>(a.unitsPerEmployeeHour??Infinity)-(b.unitsPerEmployeeHour??Infinity)).map(r=>[r.order,r.machine,r.product,fmt(r.avgWorkers,1),fmt(ratio(r.produced,r.avgWorkers),1),fmt(ratio(r.productionHours,r.avgWorkers),1),fmt(r.unitsPerEmployeeHour,1),fmt(lostHours(r),1),fmt(r.disturbanceMin,1),r.avgWorkers>0&&r.avgWorkers<median(c.valid.map(x=>x.avgWorkers))&&r.availability<50?'Lower staffing + availability <50%':'—'])),'Review signal compares headcount with the filtered median. Compare equivalent products and machines before making staffing decisions.');}
function renderEfficiency(c){const size=r=>r.sizeQuartile==='Q1'?'Small (Q1)':r.sizeQuartile==='Q4'?'Large (Q4)':'Medium (Q2–Q3)',rows=['Small (Q1)','Medium (Q2–Q3)','Large (Q4)'].map(label=>{const rr=c.valid.filter(r=>size(r)===label);return [label,rr.length,fmt(total(rr,'produced')),fmt(ratio(total(rr,'produced'),total(rr,'usageHours')),1),fmt(median(rr.map(r=>r.availability)),1),fmt(total(rr,'disturbanceMin'),1)]});return section('Order Size, Throughput & Production Efficiency','Size groups use global produced-quantity quartiles: small Q1, medium Q2–Q3, large Q4. Recorded rejects have sparse coverage; produced quantity is not asserted to be good quantity. Utilization needs a scheduled capacity denominator.')+cards([
 ['Produced units',fmt(total(c.f,'produced'))],['Ordered quantity',fmt(total(c.f,'orderedQty')),'',`${c.f.filter(r=>r.orderedQty!=null).length}/${c.f.length} orders covered`],['Target achievement',fmt(percentage(total(c.f.filter(r=>r.orderedQty>0),'produced'),total(c.f.filter(r=>r.orderedQty>0),'orderedQty')),1),'%'],['Recorded rejects',fmt(total(c.f,'rejectQty')),'',`${c.f.filter(r=>r.hasRejectRecord).length}/${c.f.length} orders have reject records`],['Good quantity','Unverified'],['Capacity utilization','Unavailable']
 ])+panel('Size comparison',dataTable(['Size','Orders','Output','Units / usage h','Median availability %','Stoppage min'],rows))+panel('Least efficient orders first',dataTable(['Order','Product','Machine','Size','Ordered','Produced','Recorded rejects','Units / h','Actual cycle sec','Target cycle sec','Performance %'],[...c.valid].sort((a,b)=>(a.performance??Infinity)-(b.performance??Infinity)).map(r=>[r.order,r.product,r.machine,size(r),fmt(r.orderedQty),fmt(r.produced),r.hasRejectRecord?fmt(r.rejectQty):'Unknown',fmt(r.grossRate*60,1),fmt(ratio(r.productionHours*3600,r.produced),2),fmt(ratio(60,r.targetRate),2),fmt(r.performance,1)])),'Actual cycle uses production time per produced unit; target cycle uses the order master target rate. Performance uses period-level targets.');}
function renderPackaging(c){return section('Packaging Cost & Cost per Produced Unit','The supplied ERP file contains units per box and pallet, but no packaging price, type, material consumption or cost ledger. Cost rankings and monthly € trends cannot be calculated from these sources.')+cards([
 ['Total packaging cost','Unavailable','€'],['Cost / produced unit','Unavailable','€/unit'],['Cost / order','Unavailable','€/order'],['Packaging consumption','Unavailable'],['Pack-size coverage',fmt(c.f.filter(r=>r.unitsBox>0).length),'orders',`${c.f.length} selected MES orders`]
 ])+panel('Inputs needed to calculate costs',dataTable(['Input','Join / grain','Calculation'],[['Packaging consumption','Order + material + date','Quantity actually consumed, including waste'],['Packaging purchase price','Material + currency + effective date','Consumed quantity × unit price'],['Packaging type / bill of materials','Product + material','Compare equivalent packaging configurations'],['Production cost ledger','Order + cost category','Packaging cost / total production cost']]))+panel('Available packaging attributes',dataTable(['Order','Product','Produced quantity','Units per box'],c.f.map(r=>[r.order,r.product,fmt(r.produced),fmt(r.unitsBox)])),'Units per box describe pack size; they do not establish actual packaging consumption or cost.');}
function renderManagement(c){const p=selectedPeriods(c),rr=reasonRows(c),exceptions=c.f.filter(r=>r.excelQty==null||(r.qtyDeltaPct!=null&&Math.abs(r.qtyDeltaPct)>5)),loss=p.reduce((s,r)=>s+lostHours(r),0),run=c.f.filter(r=>r.plannedRunMin>0);return section('Where Are We Losing Money or Capacity?','Capacity and reconciliation exceptions use the current filters. Energy is a separate KM1 monitoring window. Monetary losses require confirmed cost inputs.')+cards([
 ['Production output',fmt(total(c.f,'produced')),'units'],['Target achievement',fmt(percentage(total(c.f.filter(r=>r.orderedQty>0),'produced'),total(c.f.filter(r=>r.orderedQty>0),'orderedQty')),1),'%'],['Availability proxy',fmt(percentage(total(p,'productionHours'),total(p,'usageHours')),1),'%'],['Non-production time',fmt(loss,1),'h'],['Stoppage time',fmt(total(rr,'minutes')/60,1),'h','Recorded reasons; overlaps other loss measures'],['Labor productivity',fmt(ratio(total(p,'produced'),total(p,'employeeHours')),1),'units/h'],['MES ↔ Excel match',fmt(percentage(c.matched.length,c.f.length),1),'%'],['Recorded scrap proxy',fmt(percentage(total(c.f,'rejectQty'),total(c.f,'produced')+total(c.f,'rejectQty')),2),'%','Sparse capture; not a complete scrap rate'],['Packaging cost','Unavailable','€'],['Energy consumption',fmt(D.energy.totalDelta,3),'meter units','Global KM1 pilot'],['Energy cost','Unavailable','€'],['On-time production','Unavailable','','Validated schedule required']
 ])+`<div class="grid3">${panel('Data mismatch',`<p class="metric red">${exceptions.length} orders</p><p>No Excel match or quantity variance above ±5%.</p>`)}${panel('Runtime exception',`<p class="metric amber">${run.filter(r=>r.usageHours*60>r.plannedRunMin).length} orders</p><p>Usage exceeds target-rate runtime. Check stoppages, batch size and targets.</p>`)}${panel('Largest recorded loss reason',`<p class="metric">${esc(rr[0]?.reason||'—')}</p><p>${fmt(rr[0]?.minutes,1)} recorded minutes. Validate event overlap before estimating savings.</p>`)}</div>`+panel('Top 5 orders requiring capacity review',dataTable(['Order','Product','Machine','Non-production h','Stoppage min','Data quality'],[...c.f].sort((a,b)=>lostHours(b)-lostHours(a)).slice(0,5).map(r=>[r.order,r.product,r.machine,fmt(lostHours(r),1),fmt(r.disturbanceMin,1),reconciliationStatus(r)])),'Ranked by non-production hours, not estimated financial loss. Staffing and energy waste cannot be ranked conclusively from the available inputs.');}
function renderEnergyMonitoring(){const e=D.energy;const byMeter=e.components.map(m=>{const rr=e.intervals.filter(r=>r.meter===m.meter),rates=rr.map(r=>r.delta/r.hours),med=median(rates);return {...m,intervals:rr,peaks:rr.filter(r=>med>0&&r.delta/r.hours>3*med)}});return section('Energy Monitoring / Pilot Analysis','Consumption = current cumulative reading − previous reading for each meter. Invalid samples and counter decreases are excluded and flagged. This short sample cannot establish product efficiency rankings.')+cards([
 ['Total consumption',fmt(e.totalDelta,5),'meter units','Unit unconfirmed; kWh unavailable'],['Energy cost','Unavailable','€','Confirm kWh and electricity tariff'],['Energy / produced unit','Unavailable','','Exact overlapping production output required'],['Cost / produced unit','Unavailable','€/unit'],['Idle / stoppage energy','Unavailable','%','Validated machine-state intervals required'],['Observation window',fmt(e.windowHours,2),'h'],['Invalid / reset samples',fmt(e.invalidIntervals)],['Rate peaks',fmt(byMeter.reduce((s,m)=>s+m.peaks.length,0)),'','Rate >3× same-meter median; heuristic']
 ])+panel('Energy by meter / component',barList(e.components.map(r=>({label:r.component,value:r.delta})),' units'))+section('Consumption over time','Each point is one valid consecutive-reading interval. Rates account for unequal sampling durations. Hover over a point for interval consumption; gaps are not interpolated.')+`<div class="grid2">${byMeter.map(m=>panel(m.component,energyTrend(m.intervals),`${m.meter} · ${m.peaks.length} candidate peaks (>3× median rate)`)).join('')}</div>`+panel('Energy allocated to overlapping orders',dataTable(['Order','Allocated meter units'],e.orderAllocation.map(r=>[r.order,fmt(r.delta,5)])),`Estimated by timestamp overlap, assuming constant consumption within each meter interval. ${fmt(e.unallocatedDelta,5)} units remain unallocated in gaps or ambiguous overlaps. Production periods extend beyond the pilot, so their full output cannot serve as an energy denominator.`)+panel('Production allocation readiness',dataTable(['Requested metric','Current status'],[['Energy per order / production hour','Order consumption allocated by time overlap above; production-hour intensity still requires matching runtime within the pilot'],['Productive vs idle / stoppage energy','Requires validated state-code mapping and nonoverlapping status intervals'],['Output vs energy scatter','Unavailable until the same observation windows have validated output and energy'],['kWh and €','Meter unit and tariff not supplied']]))+panel('Meter audit',dataTable(['Meter','Component','First reading time','Last reading time','Readings','Valid delta'],e.components.map(r=>[r.meter,r.component,r.first,r.last,r.readings,fmt(r.delta,5)])));}
function energyTrend(rows){if(!rows.length)return '<div class="empty">No valid meter intervals</div>';const w=620,h=220,p=40,min=Math.min(...rows.map(r=>Date.parse(r.start))),max=Math.max(...rows.map(r=>Date.parse(r.end))),rate=Math.max(...rows.map(r=>r.delta/r.hours),1e-9),x=t=>p+(Date.parse(t)-min)/(max-min||1)*(w-2*p),y=r=>h-p-r/rate*(h-2*p);return `<svg viewBox="0 0 ${w} ${h}" class="svgchart" role="img" aria-label="Energy consumption rate over time"><text x="${p}" y="15" class="tick">Meter units / hour (interval average)</text><line x1="${p}" x2="${w-p}" y1="${h-p}" y2="${h-p}" class="axis"/>${rows.map(r=>`<line x1="${x(r.start)}" x2="${x(r.end)}" y1="${y(r.delta/r.hours)}" y2="${y(r.delta/r.hours)}" class="line-a"/><circle cx="${x(r.end)}" cy="${y(r.delta/r.hours)}" r="2" class="point"><title>${esc(r.start)} → ${esc(r.end)}: ${fmt(r.delta,6)} units; ${fmt(r.delta/r.hours,4)} units/h</title></circle>`).join('')}<text x="2" y="${p}" class="tick">${fmt(rate,2)}</text><text x="${p}" y="${h-10}" class="tick">${esc(rows[0].start.slice(11))}</text><text x="${w-p}" y="${h-10}" text-anchor="end" class="tick">${esc(rows[rows.length-1].end.slice(11))}</text></svg>`}

function timeTrend(rows){
 if(!rows.length)return '<div class="empty">No recorded periods for these filters</div>';
 const w=620,h=230,p=42,max=Math.max(1,...rows.map(r=>r.value));
 const x=i=>p+i/Math.max(1,rows.length-1)*(w-2*p),y=v=>h-p-v/max*(h-2*p);
 const every=Math.max(1,Math.ceil(rows.length/6));
 return `<svg viewBox="0 0 ${w} ${h}" class="svgchart" role="img" aria-label="Non-production hours by date"><text x="${p}" y="16" class="tick">Non-production hours</text><line x1="${p}" x2="${w-p}" y1="${h-p}" y2="${h-p}" class="axis"/><text x="2" y="${p}" class="tick">${fmt(max)}</text><polyline points="${rows.map((r,i)=>`${x(i)},${y(r.value)}`).join(' ')}" class="line-a"/>${rows.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r.value)}" r="3" class="point"><title>${esc(r.label)}: ${fmt(r.value,1)} hours</title></circle>${i%every===0?`<text x="${x(i)}" y="${h-16}" text-anchor="middle" class="tick">${esc(r.label)}</text>`:''}`).join('')}</svg>`;
}
