async function loadDashboard(){
 try {
 const response=await fetch("data/dashboard.json",{cache:"no-cache"});
 if(!response.ok)throw new Error(`Data request failed (HTTP ${response.status})`);
 const payload=await response.json();
 if(payload.meta?.schemaVersion!==3)throw new Error("Dashboard data schema mismatch. Rebuild the dashboard dataset.");
 startDashboard(payload.operations,payload.energy);
 document.getElementById("loadStatus").hidden=true;
 }catch(error){const status=document.getElementById("loadStatus");status.textContent=`Could not load dashboard: ${error.message}. Serve the project over HTTP and run python scripts/build_dashboard_data.py if needed.`;status.setAttribute("role","alert");console.error(error);}
}
function startDashboard(D,EN){
const $=id=>document.getElementById(id); const NS='http://www.w3.org/2000/svg';
function n(v){v=Number(v);return isFinite(v)?v:0} function fmt(v,d=0){return (v===null||v===undefined||!isFinite(Number(v)))?'-':Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d})} function pct(v,d=1){return v!=null&&Number.isFinite(Number(v))?fmt(v*100,d)+'%':'-'}
function median(a){a=a.filter(v=>v!==null&&v!==undefined&&isFinite(v)).map(Number).sort((a,b)=>a-b);if(!a.length)return null;let m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function pearson(p){p=p.filter(([x,y])=>x!=null&&y!=null&&Number.isFinite(Number(x))&&Number.isFinite(Number(y)));if(p.length<3)return null;let mx=p.reduce((s,z)=>s+z[0],0)/p.length,my=p.reduce((s,z)=>s+z[1],0)/p.length,num=0,dx=0,dy=0;for(const[x,y]of p){num+=(x-mx)*(y-my);dx+=(x-mx)**2;dy+=(y-my)**2}return dx>0&&dy>0?num/Math.sqrt(dx*dy):null}
function regression(p){p=p.filter(([x,y])=>x!=null&&y!=null&&Number.isFinite(Number(x))&&Number.isFinite(Number(y)));if(p.length<2)return null;let mx=p.reduce((s,z)=>s+z[0],0)/p.length,my=p.reduce((s,z)=>s+z[1],0)/p.length,den=p.reduce((s,z)=>s+(z[0]-mx)**2,0);if(!den)return null;let b=p.reduce((s,z)=>s+(z[0]-mx)*(z[1]-my),0)/den,a=my-b*mx,xs=p.map(z=>z[0]),lo=Math.min(...xs),hi=Math.max(...xs);return[{x:lo,y:a+b*lo},{x:hi,y:a+b*hi}]}
function E(tag,a={},txt=null){let e=document.createElementNS(NS,tag);for(let[k,v]of Object.entries(a))e.setAttribute(k,v);if(txt!==null)e.textContent=txt;return e} function svgBase(id,w=680,h=235){let host=$(id);host.innerHTML='';let s=E('svg',{viewBox:`0 0 ${w} ${h}`,preserveAspectRatio:'xMidYMid meet'});host.appendChild(s);return s} function t(s,x,y,txt,opt={}){s.appendChild(E('text',{x,y,fill:opt.fill||'#92a8c3','font-size':opt.size||10,'text-anchor':opt.anchor||'middle','font-family':'Segoe UI,Arial',...opt.attrs},txt))} function trunc(x,l=18){x=String(x??'');return x.length>l?x.slice(0,l-1)+'…':x}
function drawVBar(id,labels,vals,colors=['#38bdf8']){let s=svgBase(id),W=680,H=235,L=50,R=14,T=18,B=48,iw=W-L-R,ih=H-T-B,max=Math.max(1,...vals.map(v=>isFinite(v)?v:0))*1.12;for(let i=0;i<=4;i++){let y=T+ih-i*ih/4;s.appendChild(E('line',{x1:L,y1:y,x2:W-R,y2:y,stroke:'rgba(146,168,195,.14)'}));t(s,L-7,y+3,fmt(max*i/4,max<20?1:0),{anchor:'end',size:8})}let bw=iw/Math.max(labels.length,1)*.62;labels.forEach((lab,i)=>{let v=isFinite(vals[i])?vals[i]:0,x=L+(i+.5)*iw/labels.length,y=T+ih-v/max*ih;s.appendChild(E('rect',{x:x-bw/2,y,width:bw,height:Math.max(0,T+ih-y),rx:5,fill:colors[i%colors.length]}));t(s,x,y-5,fmt(v,v<10?1:0),{fill:'#edf5ff',size:8});t(s,x,H-24,trunc(lab,14),{size:8})})}
function drawGrouped(id,labels,series){let s=svgBase(id),W=680,H=205,L=50,R=15,T=15,B=42,iw=W-L-R,ih=H-T-B,max=Math.max(1,...series.flatMap(x=>x.vals).map(Number))*1.12;for(let i=0;i<=4;i++){let y=T+ih-i*ih/4;s.appendChild(E('line',{x1:L,y1:y,x2:W-R,y2:y,stroke:'rgba(146,168,195,.12)'}))}let group=iw/labels.length,bw=group/(series.length+1);labels.forEach((lab,i)=>{series.forEach((ss,j)=>{let v=Number(ss.vals[i]||0),x=L+i*group+(j+1)*bw,y=T+ih-v/max*ih;s.appendChild(E('rect',{x:x-bw*.42,y,width:bw*.84,height:T+ih-y,rx:4,fill:ss.color}))});t(s,L+(i+.5)*group,H-20,trunc(lab,11),{size:8})});series.forEach((ss,j)=>{let x=L+j*150;s.appendChild(E('rect',{x,y:2,width:10,height:10,rx:2,fill:ss.color}));t(s,x+15,11,ss.name,{anchor:'start',size:8})})}
function drawHBar(id,labels,vals,colors=['#f59e0b'],cum=null){let s=svgBase(id),W=680,H=235,L=155,R=62,T=12,B=15,iw=W-L-R,ih=H-T-B,max=Math.max(1,...vals.map(v=>isFinite(v)?v:0))*1.08,row=ih/Math.max(labels.length,1);labels.forEach((lab,i)=>{let y=T+i*row+row*.16,h=row*.58,w=(Number(vals[i])||0)/max*iw;t(s,L-7,y+h*.72,trunc(lab,20),{anchor:'end',size:8});s.appendChild(E('rect',{x:L,y,width:w,height:h,rx:4,fill:colors[i%colors.length]}));t(s,L+w+5,y+h*.72,fmt(vals[i],0),{anchor:'start',fill:'#edf5ff',size:8});if(cum)t(s,W-R+6,y+h*.72,fmt(cum[i],0)+'%',{anchor:'start',fill:'#7dd3fc',size:8})})}
function drawStacked(id,parts){let s=svgBase(id,680,195),W=680,L=35,R=25,T=60,total=parts.reduce((a,b)=>a+n(b.v),0)||1,x=L,iw=W-L-R;parts.forEach(p=>{let w=n(p.v)/total*iw;s.appendChild(E('rect',{x,y:T,width:w,height:50,fill:p.c}));if(w>58)t(s,x+w/2,T+30,pct(n(p.v)/total,1),{fill:'#07111f',size:10});x+=w});let y=138;parts.forEach((p,i)=>{let xx=L+(i%3)*205,yy=y+Math.floor(i/3)*26;s.appendChild(E('rect',{x:xx,y:yy,width:11,height:11,rx:2,fill:p.c}));t(s,xx+16,yy+10,trunc(p.l,21),{anchor:'start',size:8})})}
function drawScatter(id,pts,opt={}){let s=svgBase(id),W=680,H=235,L=55,R=20,T=18,B=45,iw=W-L-R,ih=H-T-B;if(!pts.length){t(s,W/2,H/2,'No valid points under current filter',{size:11});return}let xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);if(xmax===xmin)xmax=xmin+1;if(ymax===ymin)ymax=ymin+1;xmin=Math.min(0,xmin);ymin=Math.min(0,ymin);for(let i=0;i<=4;i++){let x=L+i*iw/4,y=T+ih-i*ih/4;s.appendChild(E('line',{x1:x,y1:T,x2:x,y2:T+ih,stroke:'rgba(146,168,195,.1)'}));s.appendChild(E('line',{x1:L,y1:y,x2:W-R,y2:y,stroke:'rgba(146,168,195,.1)'}));t(s,x,H-24,fmt(xmin+(xmax-xmin)*i/4,1),{size:8});t(s,L-7,y+3,fmt(ymin+(ymax-ymin)*i/4,1),{anchor:'end',size:8})}let sx=x=>L+(x-xmin)/(xmax-xmin)*iw,sy=y=>T+ih-(y-ymin)/(ymax-ymin)*ih;pts.forEach(p=>s.appendChild(E('circle',{cx:sx(p.x),cy:sy(p.y),r:p.r||3.2,fill:p.c||'rgba(56,189,248,.72)'})));let reg=opt.reg?regression(pts.map(p=>[p.x,p.y])):null;if(reg)s.appendChild(E('line',{x1:sx(reg[0].x),y1:sy(reg[0].y),x2:sx(reg[1].x),y2:sy(reg[1].y),stroke:'#ef4444','stroke-width':2}));t(s,W/2,H-5,opt.xLabel||'',{size:8});let yl=E('text',{x:13,y:H/2,fill:'#92a8c3','font-size':8,'font-family':'Segoe UI,Arial',transform:`rotate(-90 13 ${H/2})`},opt.yLabel||'');s.appendChild(yl)}
function drawLine(id,rows,xKey,yKey){let s=svgBase(id),W=680,H=235,L=50,R=18,T=18,B=45,iw=W-L-R,ih=H-T-B;if(!rows.length){t(s,W/2,H/2,'No data',{size:11});return}let ys=rows.map(r=>n(r[yKey])),max=Math.max(1,...ys)*1.08,min=0;for(let i=0;i<=4;i++){let y=T+ih-i*ih/4;s.appendChild(E('line',{x1:L,y1:y,x2:W-R,y2:y,stroke:'rgba(146,168,195,.12)'}));t(s,L-7,y+3,fmt(max*i/4,0),{anchor:'end',size:8})}let pts=rows.map((r,i)=>[L+i*iw/Math.max(rows.length-1,1),T+ih-(n(r[yKey])-min)/(max-min)*ih]);s.appendChild(E('polyline',{points:pts.map(p=>p.join(',')).join(' '),fill:'none',stroke:'#38bdf8','stroke-width':2.2}));let step=Math.max(1,Math.floor(rows.length/6));rows.forEach((r,i)=>{if(i%step===0||i===rows.length-1)t(s,pts[i][0],H-23,String(r[xKey]).slice(5),{size:8})})}
function drawCoverage(id,mes,excel,matched){let s=svgBase(id),W=680,H=235,L=85,R=30,T=25,B=30,max=Math.max(1,mes,excel)*1.12;let vals=[mes,excel,matched],labs=['MES orders','Excel orders','Matched'];let cols=['#38bdf8','#a78bfa','#22c55e'];vals.forEach((v,i)=>{let y=T+i*58,w=(W-L-R)*v/max;t(s,L-8,y+24,labs[i],{anchor:'end',size:9});s.appendChild(E('rect',{x:L,y,width:w,height:34,rx:6,fill:cols[i]}));t(s,L+w+7,y+23,fmt(v,0),{anchor:'start',fill:'#edf5ff',size:10})})}
const compMap=new Map(D.comparisons.map(x=>[String(x.order),x]));
const operationDates=D.union.map(x=>x.order_date).filter(Boolean).sort();
const opsDefaults={from:operationDates[0]||'',to:operationDates[operationDates.length-1]||''};
const opsState={machine:'ALL',product:'ALL',shift:'ALL',size:'ALL',status:'ALL',...opsDefaults};
function srcClass(u){let c=compMap.get(String(u.order));if(u.status==='MES_ONLY')return'MES_ONLY';if(u.status==='EXCEL_ONLY')return'EXCEL_ONLY';if(!c||c.qty_diff_pct==null)return'MATCHED';return Math.abs(c.qty_diff_pct)<=.05?'LE5':'GT5'}
function passDate(d,st){return !d||(!st.from||d>=st.from)&&(!st.to||d<=st.to)}
function opsFiltered(){return D.union.filter(u=>(opsState.machine==='ALL'||u.machine===opsState.machine)&&(opsState.product==='ALL'||u.product===opsState.product)&&(opsState.size==='ALL'||u.size_bucket===opsState.size)&&passDate(u.order_date,opsState)&&(()=>{let sh=(u.mes&&u.mes.shift_primary)||'Unknown';return opsState.shift==='ALL'||sh===opsState.shift})()&&(opsState.status==='ALL'||(opsState.status==='MATCHED'?u.status==='MATCHED':srcClass(u)===opsState.status)))}
function opsMes(){return opsFiltered().filter(u=>u.mes).map(u=>u.mes)} function opsMatched(){let ids=new Set(opsFiltered().filter(u=>u.status==='MATCHED').map(u=>String(u.order)));return D.comparisons.filter(c=>ids.has(String(c.order)))} function opsIDs(){return new Set(opsFiltered().map(u=>String(u.order)))}
function standardMin(m){return m&&m.target_rate>0&&m.produced>0?m.produced/m.target_rate:null} function lossMin(m){let st=standardMin(m);return st!=null?Math.max(0,m.usage_h*60-st):null}
function updateOpsProducts(){let base=D.union.filter(u=>(opsState.machine==='ALL'||u.machine===opsState.machine)&&passDate(u.order_date,opsState));let vals=[...new Set(base.map(x=>x.product).filter(Boolean))].sort();$('oProduct').innerHTML='<option value="ALL">All products</option>'+vals.map(v=>`<option>${v}</option>`).join('');if(opsState.product!=='ALL'&&!vals.includes(opsState.product))opsState.product='ALL';$('oProduct').value=opsState.product}
function renderOpsSummary(){let parts=[];if(opsState.machine!=='ALL')parts.push(`<b>${opsState.machine}</b>`);if(opsState.product!=='ALL')parts.push(`product <b>${opsState.product}</b>`);if(opsState.shift!=='ALL')parts.push(`shift <b>${opsState.shift}</b>`);if(opsState.size!=='ALL')parts.push(`<b>${opsState.size}</b>`);if(opsState.status!=='ALL')parts.push(`<b>${opsState.status}</b>`);parts.push(`${opsState.from} → ${opsState.to}`);$('oSummary').innerHTML='Showing: '+parts.join(' · ')}
function renderOpsKPIs(){let u=opsFiltered(),mes=u.filter(x=>x.mes).length,exc=u.filter(x=>x.excel).length,mat=u.filter(x=>x.status==='MATCHED').length,union=u.length,c=opsMatched(),within=c.filter(x=>x.qty_diff_pct!=null&&Math.abs(x.qty_diff_pct)<=.05).length,m=opsMes().filter(x=>x.usage_h>0),avail=median(m.map(x=>x.availability)),lost=m.map(lossMin).filter(v=>v!=null).reduce((s,v)=>s+v,0)/60,dist=median(m.map(x=>x.disturbance_min_per_usage_h));let cards=[['MES orders',mes,'','execution population',''],['Excel orders',exc,'','operator-list population',''],['Matched orders',mat,'','same normalized order key','good'],['Order overlap',union?mat/union:null,'%','matched / union','good'],['Qty within ±5%',c.length?within/c.length:null,'%','matched orders','good'],['Median availability',avail,'%','production / usage time','warn'],['Loss vs standard',lost,'h','usage - produced/target rate','bad'],['Disturbance intensity',dist,'min/h','median type-1 disturbance','bad']];$('opsKPIs').innerHTML=cards.map(x=>`<div class="kpi ${x[4]}"><div class="label">${x[0]}</div><div class="value">${x[2]=='%'?fmt(x[1]!=null?x[1]*100:null,1):fmt(x[1],x[2]=='min/h'?1:(x[2]=='h'?0:0))}<span class="unit">${x[2]}</span></div><div class="mini">${x[3]}</div></div>`).join('')}
function renderCoverage(){let u=opsFiltered(),mes=u.filter(x=>x.mes).length,exc=u.filter(x=>x.excel).length,mat=u.filter(x=>x.status==='MATCHED').length,c=opsMatched(),within=c.filter(x=>x.qty_diff_pct!=null&&Math.abs(x.qty_diff_pct)<=.05).length;drawCoverage('cCoverage',mes,exc,mat);$('mCoverage').innerHTML=`<span class="chip">Union <b>${u.length}</b></span><span class="chip">MES only <b>${u.filter(x=>x.status==='MES_ONLY').length}</b></span><span class="chip">Excel only <b>${u.filter(x=>x.status==='EXCEL_ONLY').length}</b></span><span class="chip">Qty ≤5% <b>${c.length?pct(within/c.length):'-'}</b></span>`;let rows=[...c].sort((a,b)=>Math.abs(n(b.qty_diff_pct))-Math.abs(n(a.qty_diff_pct))).slice(0,7);$('tQty').innerHTML=rows.length?rows.map(x=>`<tr><td>${x.order}</td><td>${x.machine||'-'}</td><td class="num">${fmt(x.mes_qty)}</td><td class="num">${fmt(x.excel_qty)}</td><td class="num ${Math.abs(n(x.qty_diff_pct))>.05?'badtext':''}">${fmt(n(x.qty_diff_pct)*100,1)}%</td></tr>`).join(''):'<tr><td colspan="5">No matched orders in filter.</td></tr>';$('vCoverage').innerHTML=`<b>Validation:</b> MES = distinct normalized OrderNo in 2026 production periods; Excel = distinct normalized Auftragskarte Nr.; matched = set intersection. Quantity variance = (MES quantity − Excel quantity) / Excel quantity. Default exception band = ±5%.`}
function renderDelay(){let m=opsMes().filter(x=>x.usage_h>0),prod=m.reduce((s,x)=>s+n(x.production_sec),0),stop=m.reduce((s,x)=>s+n(x.org_stop_sec)+n(x.tech_stop_sec),0),other=m.reduce((s,x)=>s+Math.max(0,n(x.usage_sec)-n(x.production_sec)-n(x.org_stop_sec)-n(x.tech_stop_sec)),0);drawStacked('cTimeSplit',[{l:'Active production',v:prod,c:'#22c55e'},{l:'Org + technical stop',v:stop,c:'#ef4444'},{l:'Other non-production',v:other,c:'#f59e0b'}]);let vals=m.map(x=>({m:x,loss:lossMin(x),std:standardMin(x)})).filter(x=>x.loss!=null).sort((a,b)=>b.loss-a.loss);let medLoss=median(vals.map(x=>x.loss));$('mDelay').innerHTML=`<span class="chip">Median loss/order <b>${fmt(medLoss!=null?medLoss/60:null,1)} h</b></span><span class="chip">Orders with standard <b>${vals.length}</b></span><span class="chip">Median availability <b>${pct(median(m.map(x=>x.availability)))}</b></span>`;$('tDelay').innerHTML=vals.slice(0,7).map(x=>`<tr><td>${x.m.order}</td><td>${x.m.machine}</td><td class="num">${fmt(x.m.usage_h,1)}</td><td class="num">${fmt(x.std/60,1)}</td><td class="num badtext">${fmt(x.loss/60,1)}</td><td class="num">${pct(x.m.availability)}</td></tr>`).join('');$('vDelay').innerHTML=`<b>Validation:</b> Standard run minutes = Produced units / TargetUnitsPerMinute. Loss vs standard = max(MES usage minutes − standard run minutes, 0). Time composition uses CalcProductionTime, StoppageTimeOrganiz, StoppageTimeTechnic and CalcUsageTime. This is an operational loss proxy, not a scheduled due-date lateness measure.`}
function renderPareto(){let ids=opsIDs(),tot={};D.mes_reason_events.forEach(e=>{if(ids.has(String(e.order)))tot[e.reason]=(tot[e.reason]||0)+e.minutes});let sum=Object.values(tot).reduce((s,x)=>s+x,0),arr=Object.entries(tot).sort((a,b)=>b[1]-a[1]).slice(0,8),cum=0,cums=arr.map(x=>{cum+=x[1];return sum?100*cum/sum:0});drawHBar('cPareto',arr.length?arr.map(x=>x[0]):['No data'],arr.length?arr.map(x=>x[1]):[0],['#f59e0b'],arr.length?cums:null);$('mPareto').innerHTML=arr.length?`<span class="chip">Top reason <b>${arr[0][0]}</b></span><span class="chip">Top 3 share <b>${pct(arr.slice(0,3).reduce((s,x)=>s+x[1],0)/sum)}</b></span><span class="chip">Selected disturbance min <b>${fmt(sum,0)}</b></span>`:'<span class="chip">No disturbance reasons</span>';$('vPareto').innerHTML=`<b>Validation:</b> Uses mes_stoppages rows restricted to stoppage_type_code = 1 (Störung), converts stoppage_time seconds to minutes, links by WorkRecordID, and maps reason text via the machine-group reason table. Reason labels are preserved; normalization should be introduced for production use.`}
function renderCorr(){let m=opsMes().filter(x=>x.usage_h>=.25&&x.produced>0&&isFinite(x.disturbance_min_per_usage_h)&&isFinite(x.gross_rate)),pts=m.map(x=>({x:x.disturbance_min_per_usage_h,y:x.gross_rate,r:3.2}));drawScatter('cCorr',pts,{reg:true,xLabel:'Disturbance min / usage hour',yLabel:'Gross rate units/min'});let r=pearson(pts.map(p=>[p.x,p.y]));$('mCorr').innerHTML=`<span class="chip">Pearson r <b>${fmt(r,3)}</b></span><span class="chip">Orders <b>${m.length}</b></span><span class="chip">Median throughput <b>${fmt(median(m.map(x=>x.gross_rate)),1)} u/min</b></span>`;$('vCorr').innerHTML=`<b>Validation:</b> Disturbance intensity = type-1 disturbance minutes / MES usage hours. Throughput = produced units / usage minutes. Pearson r is recalculated after every filter. Association is not proof of causation; product, machine and order-size mix can confound the result.`}
function renderDrivers(){let u=opsFiltered().filter(x=>x.mes),m=u.map(x=>x.mes).filter(x=>x.usage_h>.25&&x.produced>0),b=['Q1','Q2','Q3','Q4'],groups=b.map(z=>u.filter(x=>x.size_bucket===z).map(x=>x.mes).filter(x=>x&&x.usage_h>.25&&x.produced>0));drawGrouped('cSize',['Q1 small','Q2','Q3','Q4 large'],[{name:'Median rate u/min',color:'#38bdf8',vals:groups.map(a=>median(a.map(x=>x.gross_rate)))},{name:'Disturbance min/h',color:'#f59e0b',vals:groups.map(a=>median(a.map(x=>x.disturbance_min_per_usage_h)))}]);let defs=[['<2',w=>w<2],['2-<3',w=>w>=2&&w<3],['3-<4',w=>w>=3&&w<4],['4+',w=>w>=4]],staff=defs.map(([l,f])=>m.filter(x=>x.avg_workers!=null&&f(x.avg_workers)));drawVBar('cStaff',defs.map(x=>x[0]),staff.map(a=>median(a.map(x=>x.units_per_employee_hour))),['#22c55e']);$('mDrivers').innerHTML=`<span class="chip">Order size ↔ rate r <b>${fmt(pearson(m.map(x=>[x.produced,x.gross_rate])),3)}</b></span><span class="chip">Workers ↔ rate r <b>${fmt(pearson(m.map(x=>[x.avg_workers,x.gross_rate])),3)}</b></span><span class="chip">Workers ↔ employee productivity r <b>${fmt(pearson(m.map(x=>[x.avg_workers,x.units_per_employee_hour])),3)}</b></span>`;$('vDrivers').innerHTML=`<b>Validation:</b> Order-size groups use produced-unit quartiles. Units/employee-hour = produced units / Σ(WorkerCount × usage hours). Shift completeness is limited (many MES periods have blank Shift), so Unknown is preserved rather than imputed.`}
function renderOpsActions(){let u=opsFiltered(),m=opsMes(),c=opsMatched(),ids=opsIDs(),within=c.filter(x=>x.qty_diff_pct!=null&&Math.abs(x.qty_diff_pct)<=.05).length,r=pearson(m.filter(x=>x.usage_h>.25&&x.produced>0).map(x=>[x.disturbance_min_per_usage_h,x.gross_rate])),reasons={};D.mes_reason_events.forEach(e=>{if(ids.has(String(e.order)))reasons[e.reason]=(reasons[e.reason]||0)+e.minutes});let top=Object.entries(reasons).sort((a,b)=>b[1]-a[1])[0],acts=[['Data reliability',`${c.length?pct(within/c.length):'-'} of matched orders within ±5%.`,'Route MES/Excel exceptions to a reconciliation queue before KPI refresh.'],['Capacity loss',`${fmt(m.map(lossMin).filter(v=>v!=null).reduce((s,v)=>s+v,0)/60,0)} h above theoretical run time.`,'Target the largest time-loss orders before increasing line capacity.'],['Root cause',top?`${top[0]} is the largest selected disturbance reason.`:'No reason data','Standardize the reason taxonomy and focus improvement on top Pareto causes.'],['Planning',`Disturbance-throughput r = ${fmt(r,3)}.`,'Sequence similar products and validate staffing within comparable product/machine groups.']];$('opsActions').innerHTML=acts.map(a=>`<div class="action"><h4>${a[0]}</h4><p><b>${a[1]}</b><br>${a[2]}</p></div>`).join('')}
function renderOps(){renderOpsSummary();renderOpsKPIs();renderCoverage();renderDelay();renderPareto();renderCorr();renderDrivers();renderOpsActions()}
// ENERGY
const enState={meter:'ALL',product:'ALL',size:'ALL',from:EN.source.start.slice(0,10),to:EN.source.end.slice(0,10)};
function enDate(d){return (!enState.from||d>=enState.from)&&(!enState.to||d<=enState.to)}
function energyDaily(){return EN.daily.filter(x=>enDate(x.date))} function energyMeterDaily(){return EN.daily_meter.filter(x=>enDate(x.date)&&(enState.meter==='ALL'||x.meter===enState.meter))} function energyOrders(){return EN.orders.filter(x=>enDate(x.date||'')&&(enState.product==='ALL'||x.product===enState.product)&&(enState.size==='ALL'||x.size_bucket===enState.size))}
function selectedOrderKwh(o){if(enState.meter==='ALL')return n(o.kwh);return n((o.meter_kwh||{})[enState.meter])}
function updateEnergyProducts(){let vals=[...new Set(EN.orders.filter(x=>enDate(x.date||'')).map(x=>x.product).filter(Boolean))].sort();$('eProduct').innerHTML='<option value="ALL">All allocated products</option>'+vals.map(v=>`<option>${v}</option>`).join('');if(enState.product!=='ALL'&&!vals.includes(enState.product))enState.product='ALL';$('eProduct').value=enState.product}
function renderEnergySummary(){let parts=[`<b>KM1</b>`,`${enState.from} → ${enState.to}`];if(enState.meter!=='ALL')parts.push(`<b>${enState.meter}</b>`);if(enState.product!=='ALL')parts.push(`product <b>${enState.product}</b>`);if(enState.size!=='ALL')parts.push(`<b>${enState.size}</b>`);$('eSummary').innerHTML='Showing: '+parts.join(' · ')}
function energyStats(){let md=energyMeterDaily(),line=energyDaily(),lineKwh=enState.meter==='ALL'?line.reduce((s,x)=>s+n(x.kwh),0):md.reduce((s,x)=>s+n(x.kwh),0),alloc=line.reduce((s,x)=>s+n(x.allocated_kwh),0),dist=line.reduce((s,x)=>s+n(x.disturbance_kwh),0),idle=line.reduce((s,x)=>s+n(x.idle_unallocated_kwh),0),ord=energyOrders(),ordKwh=ord.reduce((s,o)=>s+selectedOrderKwh(o),0),units=ord.reduce((s,o)=>s+n(o.produced),0);return{lineKwh,lineTotalKwh:line.reduce((s,x)=>s+n(x.kwh),0),alloc,dist,idle,ord,ordKwh,units,coverage:line.reduce((s,x)=>s+n(x.kwh),0)?alloc/line.reduce((s,x)=>s+n(x.kwh),0):null}}
function renderEnergyKPIs(){let s=energyStats(),tar=Math.max(0,n($('tariff').value)),k1=s.units?s.ordKwh/(s.units/1000):null,cost=s.lineKwh*tar;let cards=[['Selected meter consumption',s.lineKwh,'kWh','cumulative-meter deltas',''],['Energy cost',cost,'€',`scenario @ €${fmt(tar,2)}/kWh`,'warn'],['Allocated order energy',s.ordKwh,'kWh',`${s.ord.length} orders in allocation filter`,'good'],['Energy intensity',k1,'kWh/1k','allocated energy / produced units',''],['Energy cost intensity',k1!=null?k1*tar:null,'€/1k','scenario tariff',''],['Allocation coverage',s.coverage,'%','All meters · selected calendar dates','good'],['Mapped disturbance energy',s.lineTotalKwh?s.dist/s.lineTotalKwh:null,'%','All meters · selected calendar dates','bad'],['Idle / unallocated',s.lineTotalKwh?s.idle/s.lineTotalKwh:null,'%','All meters · selected calendar dates','warn']];$('energyKPIs').innerHTML=cards.map(x=>`<div class="kpi ${x[4]}"><div class="label">${x[0]}</div><div class="value">${x[2]=='%'?fmt(x[1]!=null?x[1]*100:null,1):fmt(x[1],x[2].includes('/1k')?2:(x[2]=='€'?0:1))}<span class="unit">${x[2]}</span></div><div class="mini">${x[3]}</div></div>`).join('')}
function renderEnergyTrend(){let rows;if(enState.meter==='ALL')rows=energyDaily().map(x=>({date:x.date,kwh:x.kwh}));else{let map={};energyMeterDaily().forEach(x=>map[x.date]=(map[x.date]||0)+n(x.kwh));rows=Object.entries(map).sort().map(([date,kwh])=>({date,kwh}))}drawLine('cEnergyTrend',rows,'date','kwh');let k=rows.reduce((s,x)=>s+n(x.kwh),0);$('mEnergyTrend').innerHTML=`<span class="chip">Days <b>${rows.length}</b></span><span class="chip">Consumption <b>${fmt(k,1)} kWh</b></span><span class="chip">Median reading interval <b>${fmt(EN.quality.median_interval_seconds,0)} sec</b></span>`;$('vEnergyTrend').innerHTML=`<b>Validation:</b> For each canonical meter, interval kWh = current cumulative Total Energy Passed − previous non-null cumulative reading ordered by timestamp. Negative deltas are excluded as reset/error candidates. The supplied dashboard metadata identifies the unit as kWh.`}
function renderMeters(){let sums={};energyMeterDaily().forEach(x=>sums[x.meter]=(sums[x.meter]||0)+n(x.kwh));let arr=Object.entries(sums).sort((a,b)=>b[1]-a[1]);drawHBar('cMeter',arr.map(x=>{let m=EN.meters.find(z=>z.meter===x[0]);return m?m.component:x[0]}),arr.map(x=>x[1]),['#22d3ee']);$('mMeter').innerHTML=`<span class="chip">Physical meters <b>5</b></span><span class="chip">Raw identifiers <b>10</b></span><span class="chip">Alias change <b>03 Aug 2026</b></span>`;$('vMeter').innerHTML=`<b>Validation:</b> Raw energy_meter_device_asset_tag changes from “Weidmueller ... N1-N5” to “IFD001-IFD005 Energy meter”. Both names are mapped to the same physical meter before calculating consecutive deltas; otherwise consumption would be split into 10 false meters.`}
function renderEnergyState(){let rows=energyDaily(),tot=rows.reduce((s,x)=>s+n(x.kwh),0),alloc=rows.reduce((s,x)=>s+n(x.allocated_kwh),0),dist=rows.reduce((s,x)=>s+n(x.disturbance_kwh),0),idle=rows.reduce((s,x)=>s+n(x.idle_unallocated_kwh),0),other=Math.max(0,alloc-dist);drawStacked('cEnergyState',[{l:'Order-window excl. mapped disturbance',v:other,c:'#22c55e'},{l:'Mapped disturbance',v:dist,c:'#ef4444'},{l:'Idle / unallocated',v:idle,c:'#f59e0b'}]);$('mEnergyState').innerHTML=`<span class="chip">Order-window <b>${pct(tot?alloc/tot:null)}</b></span><span class="chip">Mapped disturbance <b>${pct(tot?dist/tot:null)}</b></span><span class="chip">Idle/unallocated <b>${pct(tot?idle/tot:null)}</b></span>`;$('vEnergyState').innerHTML=`<b>Validation:</b> This state chart always uses all five meters and the selected calendar dates; product, size and individual-meter filters do not apply because state allocation is only supplied at line/day grain. Order-window energy is timestamp-overlap allocation to KM1 MES PointStart→PointEnd intervals. Mapped disturbance energy is the overlap with the union of type-1 Störung intervals reconstructed from point_end − stoppage_time and clipped to its WorkRecord. Remaining order-window energy is a <span class="warning">production/order-window proxy</span>, not a perfect machine-state measurement.`}
function renderEnergyScatter(){let ord=energyOrders().map(o=>{let k=selectedOrderKwh(o),rate=o.usage_h?o.produced/o.usage_h:0,int=o.produced?k/(o.produced/1000):null;return{...o,sk:k,rate,int}}).filter(o=>o.produced>=1000&&o.int!=null&&isFinite(o.int));let pts=ord.map(o=>({x:o.rate,y:o.int,r:Math.max(3,Math.min(8,Math.sqrt(o.produced)/45))}));drawScatter('cEnergyScatter',pts,{reg:true,xLabel:'Produced units / usage hour',yLabel:'kWh / 1,000 units'});let top=[...ord].sort((a,b)=>b.int-a.int).slice(0,7);$('tEnergyOrders').innerHTML=top.length?top.map(o=>`<tr><td>${o.order}</td><td>${o.product||'-'}</td><td class="num">${fmt(o.sk,1)}</td><td class="num">${fmt(o.produced)}</td><td class="num badtext">${fmt(o.int,2)}</td></tr>`).join(''):'<tr><td colspan="5">No allocated orders under filter.</td></tr>';$('vEnergyScatter').innerHTML=`<b>Validation:</b> Order kWh is the sum of interval consumption × overlap seconds / interval seconds across five canonical meters. Energy intensity = allocated order kWh / (produced units / 1,000). Dates select orders by their recorded order date, retaining their full allocated energy and output. This is not energy clipped to the date range. Minimum output: 1,000 units. Product and size filters apply here; daily line charts retain all products.`}
function costCategory(e){let r=e.reason||'';if(r.includes('Packaging material'))return'Packaging handling';if(r==='Cleaning')return'Cleaning';if(r.includes('setup')||r.includes('changeover')||r.startsWith('Changeover'))return'Setup / changeover';if(e.kind==='disturbance'||r.startsWith('Disturbance'))return'Operator disturbance';return'Other'}
function renderProcessCost(){let ord=energyOrders(),ids=new Set(ord.map(o=>String(o.order))),mins={};D.manual_events.forEach(e=>{if(ids.has(String(e.order))){let c=costCategory(e);mins[c]=(mins[c]||0)+n(e.minutes)}});let arr=Object.entries(mins).sort((a,b)=>b[1]-a[1]),lc=Math.max(0,n($('lineCost').value)),costs=arr.map(x=>x[1]/60*lc);drawHBar('cProcessCost',arr.length?arr.map(x=>x[0]):['No manual cost events'],arr.length?costs:[0],['#a78bfa']);let total=costs.reduce((s,x)=>s+x,0),pack=(mins['Packaging handling']||0)/60*lc;$('processCostBig').textContent='€ '+fmt(total,0);$('processCostSmall').textContent=`Packaging-handling exposure: € ${fmt(pack,0)} · based on € ${fmt(lc,0)}/line-hour scenario`;$('mProcessCost').innerHTML=`<span class="chip">Recorded manual-process min <b>${fmt(arr.reduce((s,x)=>s+x[1],0),0)}</b></span><span class="chip">Line-cost assumption <b>€ ${fmt(lc,0)}/h</b></span>`;$('vProcessCost').innerHTML=`<b>Validation:</b> Operator Excel minute fields are classified into Cleaning, Setup/Changeover, Packaging Handling and Disturbance. Scenario process cost = recorded minutes / 60 × user-entered line cost €/h. It is an exposure estimate, not booked accounting cost. Dates select whole orders by order date; meter choice does not change operator process minutes.`}
function renderEnergy(){renderEnergySummary();renderEnergyKPIs();renderEnergyTrend();renderMeters();renderEnergyState();renderEnergyScatter();renderProcessCost()}
// CALC / TRACE
function traceOptions(){let vals=D.union.map(x=>x.order).sort();$('traceOrder').innerHTML=vals.map(v=>`<option>${v}</option>`).join('');$('traceOrder').value=vals.find(v=>D.union.find(x=>x.order===v&&x.status==='MATCHED'&&x.mes&&EN.orders.find(e=>e.order===v)))||vals.find(v=>D.union.find(x=>x.order===v&&x.status==='MATCHED'))||vals[0]}
function renderTrace(){let o=$('traceOrder').value,u=D.union.find(x=>String(x.order)===o)||{},m=u.mes||{},ex=u.excel||{},c=compMap.get(String(o)),qth=n($('qtyThreshold').value)/100,tth=n($('timeThreshold').value),q=c&&c.qty_diff_pct!=null?Math.abs(c.qty_diff_pct)>qth:false,td=c&&c.start_diff_h!=null?Math.abs(c.start_diff_h)*60>tth:false,std=standardMin(m),loss=lossMin(m);$('traceOps').innerHTML=`<table><tbody><tr><td>Order</td><td><b>${o}</b></td></tr><tr><td>Source status</td><td>${u.status||'-'}</td></tr><tr><td>Machine / Product</td><td>${u.machine||'-'} · ${u.product||'-'}</td></tr><tr><td>MES quantity</td><td>${fmt(m.produced)}</td></tr><tr><td>Excel quantity</td><td>${fmt(ex.qty)}</td></tr><tr><td>Qty variance</td><td class="${q?'badtext':'goodtext'}">${c&&c.qty_diff_pct!=null?fmt(c.qty_diff_pct*100,2)+'%':'-'}</td></tr><tr><td>MES usage / production</td><td>${fmt(m.usage_h,2)} h / ${fmt(m.production_h,2)} h</td></tr><tr><td>Target rate</td><td>${fmt(m.target_rate,2)} units/min</td></tr><tr><td>Std run time for actual output</td><td>${std!=null?fmt(std/60,2)+' h':'-'}</td></tr><tr><td>Loss vs standard</td><td>${loss!=null?fmt(loss/60,2)+' h':'-'}</td></tr><tr><td>Start-time exception</td><td class="${td?'badtext':'goodtext'}">${c&&c.start_diff_h!=null?fmt(Math.abs(c.start_diff_h)*60,1)+' min':'-'}</td></tr></tbody></table><div class="formula">Qty variance % = (MES Qty − Excel Qty) / Excel Qty\nAvailability = CalcProductionTime / CalcUsageTime\nStandard run min = Produced Units / TargetUnitsPerMinute\nLoss vs standard = MAX(Usage min − Standard run min, 0)</div>`;let ee=EN.orders.find(x=>String(x.order)===o);if(ee)$('traceEnergy').innerHTML=`<table><tbody><tr><td>Allocated energy</td><td><b>${fmt(ee.kwh,3)} kWh</b></td></tr><tr><td>Produced units</td><td>${fmt(ee.produced)}</td></tr><tr><td>kWh / 1,000 units</td><td>${fmt(ee.kwh_per_1000,3)}</td></tr><tr><td>Usage hours</td><td>${fmt(ee.usage_h,2)}</td></tr><tr><td>kWh / usage hour</td><td>${fmt(ee.kwh_per_usage_h,3)}</td></tr></tbody></table><div class="formula">Interval kWh = Current cumulative kWh − Previous cumulative kWh\nOverlap sec = MAX(0, MIN(EnergyEnd, OrderEnd) − MAX(EnergyStart, OrderStart))\nAllocated kWh = Interval kWh × Overlap sec / Interval sec\nOrder kWh = SUM(Allocated kWh across 5 canonical meters)</div>`;else $('traceEnergy').innerHTML='<div class="callout">No KM1 energy allocation exists for this selected order. Energy allocation is only available for KM1 orders whose MES time window overlaps the updated energy timeline.</div>'}
function renderCalcStatic(){
const mes=new Set(D.union.filter(x=>x.mes).map(x=>String(x.order))),excel=new Set(D.union.filter(x=>x.excel).map(x=>String(x.order))),matched=[...mes].filter(x=>excel.has(x)).length;
$('energySourceRows').textContent=fmt(EN.source.rows)+' rows';
$('mesCountFormula').textContent=`MES orders = distinct normalized execution order keys\nResult = ${mes.size}`;
$('excelCountFormula').textContent=`Excel orders = ${excel.size}\nMatched (set intersection) = ${matched}\nMES only = ${mes.size-matched}\nExcel only = ${excel.size-matched}\nUnion = ${mes.size+excel.size-matched}`;
let formulas=[['Order overlap %','Matched orders / union of normalized MES and Excel order keys'],['Qty variance %','(MES Qty − Excel Qty) / Excel Qty'],['Availability %','Σ CalcProductionTime / Σ CalcUsageTime'],['Gross production rate','Σ ProducedDuringThePeriod / (Σ CalcUsageTime / 60)'],['Disturbance intensity','Type-1 disturbance minutes / MES usage hours'],['Units / employee-hour','Produced units / Σ(WorkerCount × Usage hours)'],['Energy interval kWh','Current cumulative kWh − previous non-null cumulative kWh, same canonical meter'],['Energy cost','Valid kWh × scenario electricity tariff €/kWh'],['Energy intensity','Allocated order kWh / (Produced units / 1,000)'],['Processing cost exposure','Recorded process minutes / 60 × scenario line cost €/h']];$('formulaList').innerHTML='<table><thead><tr><th>KPI</th><th>Business / calculation logic</th></tr></thead><tbody>'+formulas.map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td></tr>`).join('')+'</tbody></table>';let q=[['Energy source rows',fmt(EN.source.rows),'Updated workbook retained all source rows'],['Missing energy values',fmt(EN.source.missing_energy),'Preserved as blank; not interpolated'],['Physical energy meters',fmt(EN.source.meters),'10 raw identifiers canonicalized to 5 meters'],['Negative cumulative deltas',fmt(EN.quality.negative_deltas),'None detected after canonical alias mapping'],['Reading gaps >5 min',fmt(EN.quality.gaps_gt_5m),'Review communication/downtime gaps'],['Reading gaps >30 min',fmt(EN.quality.gaps_gt_30m),'High-priority timeline gaps'],['Overall energy allocation coverage',pct(EN.summary.allocation_coverage),'Timestamp overlap with KM1 order windows'],['Shift completeness',`${fmt((D.summary.shift_counts||{}).F||0)} F / ${fmt((D.summary.shift_counts||{}).Unknown||0)} Unknown MES orders`,'Do not impute missing shifts']];$('qualityTable').innerHTML='<table><thead><tr><th>Check</th><th>Result</th><th>Interpretation</th></tr></thead><tbody>'+q.map(x=>`<tr><td>${x[0]}</td><td><b>${x[1]}</b></td><td>${x[2]}</td></tr>`).join('')+'</tbody></table>'}
function init(){let machines=[...new Set(D.union.map(x=>x.machine).filter(Boolean))].sort();$('oMachine').innerHTML='<option value="ALL">All machines</option>'+machines.map(x=>`<option>${x}</option>`).join('');let shifts=[...new Set(D.union.filter(x=>x.mes).map(x=>x.mes.shift_primary||'Unknown'))].sort();$('oShift').innerHTML='<option value="ALL">All shifts</option>'+shifts.map(x=>`<option>${x}</option>`).join('');$('oFrom').value=opsDefaults.from;$('oTo').value=opsDefaults.to;opsState.from=$('oFrom').value;opsState.to=$('oTo').value;updateOpsProducts();$('eMeter').innerHTML='<option value="ALL">All 5 meters</option>'+EN.meters.map(x=>`<option value="${x.meter}">${x.meter} · ${x.component}</option>`).join('');$('eFrom').value=EN.source.start.slice(0,10);$('eTo').value=EN.source.end.slice(0,10);updateEnergyProducts();traceOptions();renderCalcStatic();renderOps();renderEnergy();renderTrace()}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(b.dataset.tab).classList.add('active')}));[['oMachine','machine'],['oProduct','product'],['oShift','shift'],['oSize','size'],['oStatus','status']].forEach(([id,k])=>$(id).addEventListener('change',e=>{opsState[k]=e.target.value;if(id==='oMachine')updateOpsProducts();renderOps()}));$('oFrom').addEventListener('change',e=>{opsState.from=e.target.value;updateOpsProducts();renderOps()});$('oTo').addEventListener('change',e=>{opsState.to=e.target.value;updateOpsProducts();renderOps()});$('oReset').addEventListener('click',()=>{Object.assign(opsState,{machine:'ALL',product:'ALL',shift:'ALL',size:'ALL',status:'ALL',...opsDefaults});$('oMachine').value='ALL';$('oShift').value='ALL';$('oSize').value='ALL';$('oStatus').value='ALL';$('oFrom').value=opsState.from;$('oTo').value=opsState.to;updateOpsProducts();renderOps()});[['eMeter','meter'],['eProduct','product'],['eSize','size']].forEach(([id,k])=>$(id).addEventListener('change',e=>{enState[k]=e.target.value;renderEnergy()}));$('eFrom').addEventListener('change',e=>{enState.from=e.target.value;updateEnergyProducts();renderEnergy()});$('eTo').addEventListener('change',e=>{enState.to=e.target.value;updateEnergyProducts();renderEnergy()});$('tariff').addEventListener('input',renderEnergy);$('lineCost').addEventListener('input',renderEnergy);$('eReset').addEventListener('click',()=>{Object.assign(enState,{meter:'ALL',product:'ALL',size:'ALL',from:EN.source.start.slice(0,10),to:EN.source.end.slice(0,10)});$('eMeter').value='ALL';$('eSize').value='ALL';$('eFrom').value=enState.from;$('eTo').value=enState.to;updateEnergyProducts();$('tariff').value='0.30';$('lineCost').value='500';renderEnergy()});$('calcRefresh').addEventListener('click',renderTrace);$('traceOrder').addEventListener('change',renderTrace);$('qtyThreshold').addEventListener('input',renderTrace);$('timeThreshold').addEventListener('input',renderTrace)}
init();bind();

}
loadDashboard();
